
services:
    olgtm:
        image: grafana/otel-lgtm
        ports:
        - 3000:3000
        - 9090:9090
        - 4318:4318
        - 4317:4317

    myserver:
        build: "./"
        ports:
            - 8001:8001
        depends_on:
            - olgtm
        environment:
            - OTEL_EXPORTER_OTLP_INSECURE=true
            - OTEL_EXPORTER_OTLP_ENDPOINT=http://olgtm:4317
            - OTEL_METRICS_EXPORTER=otlp,console
            - OTEL_TRACES_EXPORTER=otlp,console
            - OTEL_SERVICE_NAME=my.little.app.otel
            - OTEL_METRIC_EXPORT_INTERVAL=1000
            - COLLECTOR_OTLP_ENABLED=true

    nginx:
        image: nginx
        volumes:
            - './etc/nginx.conf:/etc/nginx/nginx.conf'
        ports:
            - 80:80
        depends_on:
            - myserver