version: '3.1'

services:

  db:
    image: mysql
    container_name: mysql_container
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: admin123

  phpmyadmin:
    depends_on:	
    - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    restart: always
    ports: 
      - "8082:80"